# Node, Mongo, Redis, Nginx
# Minh Chu <scsilver94@gmail.com>

version: "2"
services:
  mongo-container:
    restart: always
    image: mongo:4.4
    container_name: mongodb
    ports:
      - "37017:27017" # 绑定容器的27017端口到主机的37017端口
    command: mongod
    logging:
      driver: "json-file"
    volumes: 
      - C:\docker_data\mongo_data:/data
      - C:\docker_data\mongo_data\mnt:/mnt
    # mem_limit: 200m  #最大内存使用不超过1024m

  redis:
    image: redis:3.2-alpine
    networks:
      - backend
    restart: always
    logging:
      driver: "json-file"
    ports:
      - "6379:6379"
    volumes: 
    - C:\docker_data\redis_data:/data
    - C:\docker_data\redis_data\mnt:/mnt
    command: redis-server --appendonly no --requirepass "5601564a"
    mem_limit: 200m  #最大内存使用不超过1024m

networks:
  backend:

volumes:
  mongodb:
  redis:
