version: "3"

services:
  web:
    image: 'gitlab/gitlab-ce:latest'
    container_name: gitlab
    ports:
      - '12080:80'
      - '12443:443'
      - '12022:22'
    volumes:
      - '/C/docker_data/gitlab/srv/gitlab/config:/etc/gitlab'
      - '/C/docker_data/gitlab/srv/gitlab/logs:/var/log/gitlab'
      - '/C/docker_data/gitlab/srv/gitlab/data:/var/opt/gitlab' 
