# Node, Mongo, Redis, Nginx
# Minh Chu <scsilver94@gmail.com>

version: "2"
services:
  mongo-container:
    image: mongo:3.4
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - "/data/mongo:/data/db"
    command: mongod
    logging:
      driver: "json-file"
      options:
        max-size: "100MB"
        max-file: "3"

  redis:
    image: redis:3.2-alpine
    networks:
      - backend
    restart: always
    volumes:
      - redis:/data/
    logging:
      driver: "json-file"
      options:
        max-size: "100MB"
        max-file: "3"
    ports:
      - "6379:6379"
    command: redis-server --appendonly no

networks:
  backend:

volumes:
  mongodb:
  redis:
